# Generated by Django 4.0 on 2022-01-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='sobre_nome',
            new_name='sobrenome',
        ),
    ]
